WIP: add toleration option
gardener/ops-toolbelt pull request #42
Opened 2020-12-21 14:25 UTC by jguipi

**What this PR does / why we need it**:
This PR adds the toleration option to the ops-pod script using `-t` 

**Which issue(s) this PR fixes**:
Fixes #41 

**Special notes for your reviewer**:
- none
**Release note**:
```improvement operator
This PR add the toleration option to the ops-pod script using `-t` 
```

2020-12-21 17:45 UTC, jguipi commented
execution example 
![image](https://user-images.githubusercontent.com/11049349/102806215-6e4cb200-438a-11eb-8e23-a1836ed7411d.png)

2020-12-22 06:08 UTC, neo-liang-sap approved these changes

2021-05-19 14:01 UTC, jguipi commented
cc @plkokanov

2021-06-01 13:24 UTC, jguipi commented
cc @neo-liang-sap

2021-06-10 15:01 UTC, plkokanov requested changes
I found a couple of problems with the PR. Check my comments.

2021-06-10 15:01 UTC, plkokanov commented on hacks/ops-pod
> +  -t|--toleration  Adding toleration to the pod ex.: key1=value1:key2=value2
This no longer conforms to the functionality of the script since the `--toleration` flag will copy the tolerations from the node spec.

2021-06-24 10:02 UTC, plkokanov commented
Closing this PR. A new one will be opened soon.

2021-06-24 10:02 UTC, closed without merging