wireguard and iptables
gardener/ops-toolbelt pull request #47
Opened 2021-03-12 06:33 UTC by neo-liang-sap

**What this PR does / why we need it**:
wireguard and iptables
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/ops-toolbelt/issues/46

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2021-03-12 08:23 UTC, plkokanov requested changes
Thanks for the PR!
Can you check how much the size of the image increases after adding these components?

2021-03-12 08:23 UTC, plkokanov commented on dockerfile-configs/common-components.yaml
> +      sudo apt-get ---yes install iptables-persistent
```suggestion
      sudo apt-get --yes install iptables-persistent
```

2021-03-12 08:48 UTC, neo-liang-sap commented on dockerfile-configs/common-components.yaml
> +      sudo apt-get ---yes install iptables-persistent
thanks for the catch and sorry for typo

2021-03-12 08:50 UTC, neo-liang-sap commented
Hi @plkokanov , the image increased ~15mb from my local verification
![image](https://user-images.githubusercontent.com/42594392/110915763-06878100-8353-11eb-93b1-ae2d1a33a852.png)

2021-06-25 00:39 UTC, neo-liang-sap commented
close per discussion with @plkokanov

2021-06-25 00:39 UTC, closed without merging