add img matrix infra x kubectl
gardener/ops-toolbelt pull request #50
Opened 2021-05-07 17:44 UTC by jfortin-sap

**What this PR does / why we need it**:
Add img matrix infra x kubectl to speed up ops toolbelt load times
**Which issue(s) this PR fixes**:
Fixes #37 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Add img matrix infra x kubectl to speed up ops toolbelt load times
```

2021-05-08 20:38 UTC, petersutter requested changes
please also document what needs to be done in order to support new kubectl versions (or drop deprecated versions), which scripts to run and to commit..

2021-05-08 20:38 UTC, petersutter commented on .ci/build
> +        version: v1.20.5
take the first line of `k8s_versions ` which should be the latest version

2021-05-08 20:38 UTC, petersutter commented on .ci/build
> +        --dockerfile "${GENERATED_DOCKERFILES_PATH}"/ops-toolbelt-aliyun-k$i.dockerfile
you could also have a loop for the iaas components

2021-05-08 20:38 UTC, petersutter commented on .ci/build_pipeline_definitions
> +                build: ~
same here, loop over iaas names

2021-05-08 20:38 UTC, petersutter commented on .ci/build_pipeline_definitions
> +            image: 'eu.gcr.io/gardener-project/gardener/ops-toolbelt-aws-k$i'
I don't think we should have the patch version in the image name. Major and minor version should be sufficient

2021-05-08 20:38 UTC, petersutter commented on .ci/build
> +done
I assume the `kubectl-components.yaml` file is only used temporarily to generate the dockerfile, right? Shouldn't this file be cleaned up afterwards? It anyhow only contains the contents of the last run of the loop

2021-05-14 08:24 UTC, petersutter requested changes

2021-05-14 08:24 UTC, petersutter commented on .ci/build_pipeline_definitions
> +                  build: ~
the indenting is not correct. After the fix, please re-run the script to fix `.ci/pipeline_definitions`
```suggestion
          ops-toolbelt-$iaas_provider-k$kv_short:
            registry: 'gcr-readwrite'
            image: 'eu.gcr.io/gardener-project/gardener/ops-toolbelt-$iaas_provider-k$kv_short'
            dockerfile: ops-toolbelt-$iaas_provider-k$kv_short.dockerfile
            inputs:
              steps:
                build: ~
```

2021-05-14 15:03 UTC, petersutter commented
@jfortin-sap this point is still open https://github.com/gardener/ops-toolbelt/pull/50#pullrequestreview-655018628

2021-05-14 17:34 UTC, jfortin-sap commented
@petersutter PR updated

2021-05-18 14:20 UTC, petersutter requested changes

2021-05-18 14:20 UTC, petersutter commented on README.md
> +$ .ci/build_pipeline_definitions
```suggestion
gardenctl target garden <landscape>
gardenctl kubectl get cloudprofile -o json | jq -r '.items[].spec.kubernetes.versions[] | select(.classification=="supported") | .version' |sort -r |uniq > .ci/k8s_versions
.ci/build_pipeline_definitions
```

2021-05-18 14:20 UTC, petersutter commented on README.md
> +$ .ci/build_pipeline_definitions
```suggestion
<editor> .ci/iaas-providers # to update the list
.ci/build_pipeline_definitions
```

2021-05-18 14:20 UTC, petersutter commented on README.md
> +$ .ci/build_pipeline_definitions
The command to update the `k8s_versions` file should make sure that only the latest patch version of a minor version is added.
e.g. the versions are
```
1.20.5
1.19.9
1.19.8
```

only 
```
1.20.5
1.19.9
```
should be added

2021-05-18 14:20 UTC, petersutter commented on README.md
> +To update pre-configured images supported k8s versions run then commit:
```suggestion
To update pre-configured images supported k8s versions run the following commands and then commit the resulting changes:
```

2021-05-18 14:20 UTC, petersutter commented on README.md
> +To update pre-configured images supported iaas providers run then commit:
```suggestion
To update pre-configured images supported iaas providers run the following commands and then commit the resulting changes:
```

2021-05-18 14:20 UTC, petersutter commented on README.md
> +$ .ci/build_pipeline_definitions
What about the deprecated minor versions? You can still create clusters for them

2021-05-19 15:06 UTC, jfortin-sap commented
@petersutter Updated, ready to merge?

2021-05-31 13:33 UTC, jfortin-sap commented
@petersutter ready to merge?

2021-05-31 19:00 UTC, petersutter approved these changes
/lgtm

2021-06-01 20:25 UTC, petersutter approved these changes
/lgtm

2021-06-01 20:28 UTC, merged